name: Crowdin Contributors

on: 
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    

  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      - name: Run Crowdin Contributors Bot
        uses: ./crowdin_contributors_bot
        with:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          MINIMUM_CONTRIBUTION_PER_MEMBER: ${{ secrets.MINIMUM_CONTRIBUTION_PER_MEMBER }}
          CROWDIN_ORG_API_DOMAIN: ${{ secrets.CROWDIN_ORG_API_DOMAIN }}
      - run: |
          npm install
          npm run start