name: Acknowledge Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  NEW_BRANCH: crowdin-contributors-report-$(date +'%Y-%m-%d-%H-%M-%S')

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Crowdin Contributors
        run: |
          git config --global user.email "molunorichie@gmail.com"
          git config --global user.name "Richie"
          git checkout -b $NEW_BRANCH
          npm start 
          git status
          git add README.md
          git commit -m "Generated crowdin contributors report"
          git push origin $NEW_BRANCH
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          MINIMUM_CONTRIBUTION_PER_MEMBER: ${{ secrets.MINIMUM_CONTRIBUTION_PER_MEMBER }}
          CROWDIN_ORG_API_DOMAIN: ${{ secrets.CROWDIN_ORG_API_DOMAIN }}
          START_MARKER: <!-- CROWDIN-CONTRIBUTORS-LIST:START -->
          END_MARKER: <!-- CROWDIN-CONTRIBUTORS-LIST:END -->

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $NEW_BRANCH
          base: main
          title: Generated crowdin contributors Report
          body: |
            This is an automated pull request for the generated crowdin contributors report.
