name: Acknowledge Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  NEW_BRANCH: crowdin-contributors-report-

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set New Branch Name
        id: set_branch
        run: echo "NEW_BRANCH=${NEW_BRANCH}$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Generate contributors report
        run: |
          npm install
          npm start 
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          MINIMUM_CONTRIBUTION_PER_MEMBER: ${{ secrets.MINIMUM_CONTRIBUTION_PER_MEMBER }}
          CROWDIN_ORG_API_DOMAIN: ${{ secrets.CROWDIN_ORG_API_DOMAIN }}
          START_MARKER: <!-- CROWDIN-CONTRIBUTORS-LIST:START -->
          END_MARKER: <!-- CROWDIN-CONTRIBUTORS-LIST:END -->

      - name: Commit changes
        run: |
          git config --global user.email "molunorichie@gmail.com"
          git config --global user.name "Richie"
          git checkout -b $NEW_BRANCH
          git status
          git add README.md
          git commit -m "Generated crowdin contributors report"
          git push origin $NEW_BRANCH

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.NEW_BRANCH }}                                              # If blank, default: triggered branch
          destination_branch: main                                                 # If blank, default: master
          pr_title: Update crowdin contributors in README       # Title of pull request
          pr_body: |                                                                # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*

            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          pr_reviewer: "@RealRichi3"                                     # Comma-separated list (no spaces)
          pr_assignee: "@RealRichi3"                                                # Comma-separated list (no spaces)
          pr_label: "auto-pr"                                                       # Comma-separated list (no spaces)
          pr_draft: false                                                           # Creates pull request as draft
          pr_allow_empty: true                                                      # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}   