name: Acknowledge Crowdin Contributors

on: 
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist_credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Crowdin Contributors
        run: npm start
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          MINIMUM_CONTRIBUTION_PER_MEMBER: ${{ secrets.MINIMUM_CONTRIBUTION_PER_MEMBER }}
          CROWDIN_ORG_API_DOMAIN: ${{ secrets.CROWDIN_ORG_API_DOMAIN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "RealRichi3"
          git config --global user.email "molunorichie@gmail.com"
          git add .
          git commit -m "Update README file"
          git push origin HEAD:${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
